version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
